### ISSUE TITLE
Error when using the elm prop

### ISSUE THREAD

**Issue by mniessner** [KtorZ/elm-react-component#2]
This is a great project. Thanks for sharing.

When using the elm prop, I ran into an error `You provided an argument named 'elm' but there is no corresponding port!`

I believe the issue is that on `line 21` of `elm-react-component/src/index.jsx` the string 'elm' needs to be added to the pattern of names to be filtered out. 

`.filter(x => !/^(name|children|ref|id|className|key|on[A-Z])/.test(x))` 

should become

`.filter(x => !/^(elm|name|children|ref|id|className|key|on[A-Z])/.test(x))`

**Comment by KtorZ** [comment]
Yep, you're totally right. I've just pushed a fixed to dynamically exclude all propTypes keys from that regexp such that it is much more resilient to future changes.

227fc2b817b4ae4e9cfe7333a51cba2a4e1409a8 fixed the issue.

Thanks :+1:
